import AppLayout from "@/components/layouts/AppLayout";
import { Card, CardContent } from "@/components/ui/card";

export default function PrivacyPolicy() {
  return (
    <AppLayout>
      <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white py-12">
        <div className="container mx-auto px-4 max-w-4xl">
          <Card className="shadow-lg">
            <CardContent className="p-8">
              <div className="prose prose-lg max-w-none">
                <h1 className="text-4xl font-bold text-center mb-8">Privacy Policy</h1>
                <p className="text-sm text-gray-600 text-center mb-8">Last updated: August 2025</p>
                
                <p className="mb-6">
                  Your privacy matters to us. This Privacy Policy explains how we handle your personal information.
                </p>

                <h2 className="text-2xl font-semibold mt-8 mb-4">1. Information We Collect</h2>
                <p className="mb-4">We only collect the information necessary to deliver our service:</p>
                <ul className="list-disc pl-6 mb-4">
                  <li><strong>Email address</strong> – used to send OTPs for account verification.</li>
                  <li><strong>Phone number</strong> – used to send AI-generated wake-up calls.</li>
                </ul>

                <h2 className="text-2xl font-semibold mt-8 mb-4">2. How We Use Your Information</h2>
                <p className="mb-4">We use your email and phone number solely to:</p>
                <ul className="list-disc pl-6 mb-4">
                  <li>Verify your account.</li>
                  <li>Deliver scheduled AI-generated voice calls.</li>
                </ul>
                
                <p className="mb-4">We do not:</p>
                <ul className="list-disc pl-6 mb-4">
                  <li>Share, sell, or rent your details to third parties.</li>
                  <li>Use your information for unrelated marketing without your consent.</li>
                </ul>

                <h2 className="text-2xl font-semibold mt-8 mb-4">3. AI Voice Calls</h2>
                <p className="mb-4">
                  All calls are generated by AI using Eleven Labs technology. No real human voices are used, 
                  and the content is intended for motivational and entertainment purposes.
                </p>

                <h2 className="text-2xl font-semibold mt-8 mb-4">4. Data Storage & Security</h2>
                <ul className="list-disc pl-6 mb-4">
                  <li>We store your information securely and take reasonable measures to protect it.</li>
                  <li>However, no system is 100% secure, so we cannot guarantee absolute security.</li>
                </ul>

                <h2 className="text-2xl font-semibold mt-8 mb-4">5. Third-Party Services</h2>
                <p className="mb-4">
                  We may use trusted third-party providers (e.g., for voice generation and call delivery) 
                  to operate our service. These providers are bound by confidentiality and data protection agreements.
                </p>

                <h2 className="text-2xl font-semibold mt-8 mb-4">6. Your Rights</h2>
                <p className="mb-4">You can request:</p>
                <ul className="list-disc pl-6 mb-4">
                  <li>To update or delete your information.</li>
                  <li>A copy of the personal data we hold about you.</li>
                </ul>
                <p className="mb-4">
                  Contact us at support@kickassmorning.com for any privacy-related requests.
                </p>

                <h2 className="text-2xl font-semibold mt-8 mb-4">7. Changes to This Policy</h2>
                <p className="mb-4">
                  We may update this Privacy Policy from time to time. Changes will be posted here 
                  with an updated date.
                </p>

                <h2 className="text-2xl font-semibold mt-8 mb-4">8. Contact</h2>
                <p className="mb-4">
                  If you have questions about this Privacy Policy, email us at: support@kickassmorning.com
                </p>

                <div className="mt-12 p-6 bg-gray-50 rounded-lg">
                  <p className="text-sm text-gray-600 text-center">
                    For any privacy-related concerns or requests, please don't hesitate to reach out to us.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </AppLayout>
  );
}